---
title: 'Part 3: Feature generation and exploration'
output: github_document
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This part describes the scripts that are used to execute the RWR-FGSEA framework to obtain the normalised enrichment scores and calculation of network proximity between the drug targets to various gene sets.

### 3.1. Execute RWR

+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript**   | [Scripts/Feature_generation/Execute_RWR_on_drugCombs.R](../Scripts/Feature_generation/Execute_RWR_on_drugCombs.R)                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Arguments** | Mandatory: `--disease`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|               | Optional: `--drug_target_type`, `--nproc`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**     | -   STRING_PPI_Net.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|               | -   drugCombs_targets_extended\_[disease].rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**    | rwrProbs\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary**   | The script executes random walk with restart (RWR) for each drug combination using its targets as the seeds. By default, the known drug targets are used but it can be modified to use the extended drug targets using the `drug_target_type` argument. The output is a sparse matrix containing the visiting probabilities of all nodes in the input network. The number of rows in the matrix equals the number of nodes in the input network while the number of columns equals the number of drug combinations for which the RWR was executed. |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 3.2. Calculate NES

+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript**   | [Scripts/Feature_generation/Execute_FGSEA_EfficacySafety_on_drugCombs.R](../Scripts/Feature_generation/Execute_FGSEA_EfficacySafety_on_drugCombs.R)                                                                                                                                                                                                                                                                                                                             |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | [Scripts/Feature_generation/Execute_FGSEA_Pathways_on_drugCombs.R](../Scripts/Feature_generation/Execute_FGSEA_Pathways_on_drugCombs.R)                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | [Scripts/Feature_generation/Execute_FGSEA_Miscellaneous_on_drugCombs.R](../Scripts/Feature_generation/Execute_FGSEA_Miscellaneous_on_drugCombs.R)                                                                                                                                                                                                                                                                                                                               |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Arguments** | Mandatory: `--disease`                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | Optional: `--drug_target_type`, `--nproc`                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**     | -   rwrProbs\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   Disease2Gene\_[disease]\_lib.rds                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   curatedAdr2Gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   CHG_keggPath2Gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   SMPDb_Pathway2Gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   miscellaneous_gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**    | -   fgseaNES_EfficacySafety\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                                                                                  |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   fgseaNES_Pathway\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   fgseaNES_Miscellaneous\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                                                                                   |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary**   | The scripts performs fast gene set enrichment analysis (FGSEA) of the genes selected from RWR against the mentioned libraries. The script internally uses an elbow method on the visiting probability of nodes obtained from RWR (section 3.1) to identify the genes to be used for FGSEA. The output is a list of data frames for each feature type. The data frames contains normalised enrichment scores for the drug combinations in columns against the gene sets in rows. |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 3.3. Calculate network proximity

+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript**   | [Scripts/Feature_generation/Calculate_proximity_EfficacySafety_for_drugCombs.R](../Scripts/Feature_generation/Calculate_proximity_EfficacySafety_for_drugCombs.R)                                                                                                                                                                                                                                               |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | [Scripts/Feature_generation/Calculate_proximity_Pathways_for_drugCombs.R](../Scripts/Feature_generation/Calculate_proximity_EfficacySafety_for_drugCombs.R)                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | [Scripts/Feature_generation/Calculate_proximity_Miscellaneous_for_drugCombs.R](../Scripts/Feature_generation/Calculate_proximity_Miscellaneous_for_drugCombs.R)                                                                                                                                                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Arguments** | Mandatory: `--disease`                                                                                                                                                                                                                                                                                                                                                                                          |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | Optional: `--drug_target_type`, `--nproc`                                                                                                                                                                                                                                                                                                                                                                       |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**     | -   STRING_PPI_Net.rds                                                                                                                                                                                                                                                                                                                                                                                          |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   Disease2Gene\_[disease]\_lib.rds                                                                                                                                                                                                                                                                                                                                                                            |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   curatedAdr2Gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   CHG_keggPath2Gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   SMPDb_Pathway2Gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                  |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   miscellaneous_gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                  |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**    | -   netProx_EfficacySafety\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   netProx_Pathway\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                          |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               | -   netProx_Miscellaneous\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary**   | The scripts calculates network based proximities between the targets of the drug combination and the genes sets of the mentioned feature. The primary output is a data frame containing the proximity values of the drug combinations in columns to the gene sets in rows. The data frame is stored as list of list, with the first level being the feature type and the second level being the proximity type. |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
