---
title: "Part 1: Preparing the data"
output: github_document
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This part deals with the scripts that retrieved and process the data that form the base of our framework. Here we provide details of the scripts used for building the protein-protein interaction network, parsing drug related data from DrugBank and curating the drug combination data set from FIMM DrugComb portal.

### 1.1. Building the network

+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Network_build/STRING_PPI.R](../Scripts/Network_build/STRING_PPI.R)                                                                                                                                                                                                                                                                                                                                                                                                                            |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | 9606.protein.links.detailed.v12.0.txt.gz                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | (a) STRING_PPI_Net.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|             | (b) STRING_PPI_Net_params.csv                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | Creates a protein-protein interaction network from interactions reported in the [STRING](https://string-db.org/) database. The script retrieves the source interaction file for human from STRING directly. The interactions with combined score in STRING greater than 400 are used to build the network. Only the largest connected component is retained. The output is an igraph network stored in an rds file. Additional, a csv file with the basic properties of the network is also generated. |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 1.2. Retrieving the drug target associations

+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Associations/DrugBank_Drug_Target_Associations.R](../Scripts/Associations/DrugBank_Drug_Target_Associations.R)                                                                                                 |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | drugbank_all_full_database.xml.zip                                                                                                                                                                                      |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | DrugBank_Drug_Target_associations.rds                                                                                                                                                                                   |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | The script extracts the drug-target associations from [DrugBank](https://go.drugbank.com/) and stores it as a R data frame with two columns mentioning the DrugBank drug IDs and the Ensembl gene IDs for the targets.  |
|             |                                                                                                                                                                                                                         |
|             | Note: For this script to be successfully executed, the input file must be manually downloaded from DrugBank (requires access permission) and placed in `Databases/DrugBank/` directory.                                 |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 1.3. Processing the FIMM drug combination data

+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Reference_lists/FIMMDrugComb_drugCombinations.R](../Scripts/Reference_lists/FIMMDrugComb_drugCombinations.R)                                                                                                                                               |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | (a) summary_v_1_5.csv                                                                                                                                                                                                                                               |
|             |                                                                                                                                                                                                                                                                     |
|             | (b) Thesaurus.FLAT.zip                                                                                                                                                                                                                                              |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | FimmDrugComb_drugCombinations.rds                                                                                                                                                                                                                                   |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | The script downloads the data from [FIMM DrugComb portal](https://drugcomb.fimm.fi/), extracts the drug combinations that have been tested on cancer cell lines and assigns a cancer-specific synergy level by utilising the synergy scores reported in the portal. |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 1.4. Retrieve the DrugBank drug-drug interactions

+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Reference_lists/DrugBank_DDI.R](../Scripts/Reference_lists/DrugBank_DDI.R)                                                                                                                                            |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | drugbank_all_full_database.xml.zip                                                                                                                                                                                             |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | DrugBank_DDI_processed.rds                                                                                                                                                                                                     |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | The script extracts the drug-drug interactions reported in [DrugBank](https://go.drugbank.com/) and categorises drug pairs into various classes including metabolic effect, therapeutic effect and cancer-specific ADR status. |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 1.5. Extract the targets of the drug combinations

+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript**   | [Scripts/Drug_combinations/Extract_drugCombs_and_targets.R](../Scripts/Drug_combinations/Extract_drugCombs_and_targets.R)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Arguments** | Mandatory: `--disease`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**     | (a) FimmDrugComb_drugCombinations.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|               | (b) STRING_PPI_Net.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|               | (c) DrugBank_Drug_Target_associations.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**    | (a) Drug_combination_data/drugCombs_data\_[disease].rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|               | (b) drugCombs_targets_extended\_[disease].rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary**   | The script first subsets the drug combinations for the cancer type specified using `--disease` argument from the data retrieved from [FIMM DrugComb portal](https://drugcomb.fimm.fi/) (see section 1.3). It then extracts all the known targets of the drugs involved in the combination. Additionally, it also attempts to extend the list of targets by considering the immediate neighbours of the known targets in various kinds of functionally linked protein-protein interaction networks retrieved from [OmniPath](https://omnipathdb.org/) database. Two output file are generated. The first one contains a R data frame of the with the list of drug combinations subsetted from processed DrugComb portal data. The second file also contains a data frame with information about the targets. |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
