---
title: "Part 5: De novo predictions"
output: github_document
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This part describes the scripts used to identify novel anti-cancer drug combinations from existing licensed anti-cancer drugs using the predictive system developed in the study.

### 5.1. Data for *de novo* prediction

+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript**   | [Scripts/DeNovo_predictions/DeNovo_data_1.R](../Scripts/DeNovo_predictions/DeNovo_data_1.R)                                                                                                                                                                                                                                                                                                                            |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Arguments** | Mandatory: `--disease`                                                                                                                                                                                                                                                                                                                                                                                                 |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**     | -   parsed_DrugBank_data.rds                                                                                                                                                                                                                                                                                                                                                                                           |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                        |
|               | -   cancerdrugsdb.txt (Cancer Drug Database)                                                                                                                                                                                                                                                                                                                                                                           |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                        |
|               | -   drugCombs_cat_effVadv\_[disease].rds                                                                                                                                                                                                                                                                                                                                                                               |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                        |
|               | -   09.04.2024.zip (C-DCDB)                                                                                                                                                                                                                                                                                                                                                                                            |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                        |
|               | -   STRING_PPI_Net.rds                                                                                                                                                                                                                                                                                                                                                                                                 |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**    | drugCombs_denovo1\_[disease].rds                                                                                                                                                                                                                                                                                                                                                                                       |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary**   | The script generates an initial pool of drug pairs which will be scouted to identify the novel potential effective and safe drug combinations. The drug pairs are formed by combining all possible pairs of licensed anti-cancer drugs followed by filtering our those that were included in the training set, have been into clinical trials for the specific cancer or have reported adverse drug-drug interactions. |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 5.2. Feature generation on *de novo* data

+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript**   | [Scripts/DeNovo_predictions/DeNovo_featureGeneration_1.R](../Scripts/DeNovo_predictions/DeNovo_featureGeneration_1.R)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Arguments** | Mandatory: `--disease`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|               | Optional: `--drug_target_type`, `--nproc`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**     | -   STRING_PPI_Net.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|               | -   drugCombs_denovo1\_[disease].rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|               | -   NES_EfficacySafety_selectedFeatures\_[disease]\_[drug_target_type].csv                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**    | -   fgseaNES_combinedEfficacySafety\_[disease]\_[drug_target_type].rds (in DeNovo_data_1 directory)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|               | -   plot_DeNovo_1_AD_combinedEfficacySafety\_[disease]\_[drug_target_type].tiff                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary**   | The scripts takes in the drug pairs generated in section 5.1 and implements the RWR-FGSEA (as described in part 3) framework to return a data frame of the NES for the drug combinations in column against the gene sets in rows. However, since our predictive system is based on the combined efficacy-safety library, the NES for the *de novo* data is generated only for the same. Additionally, the scripts plot the applicibility domain of the *de novo* drug combinations w.r.t the training set drug combinations by considering one efficacy and one safety feature for the scatter plot. |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 5.3. Prediction on *de novo* data

+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript**   | [Scripts/DeNovo_predictions/DeNovo_prediction_1.R](../Scripts/DeNovo_predictions/DeNovo_prediction_1.R)                                                                                                                                                                                                                                                                                                                                                             |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Arguments** | Mandatory: `--disease`                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|               | Optional: `--drug_target_type`, `--select_top_combs`                                                                                                                                                                                                                                                                                                                                                                                                                |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**     | -   parsed_DrugBank_data.rds                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|               | -   model_NES_combinedEfficacySafety\_[disease]\_[drug_target_type].rds                                                                                                                                                                                                                                                                                                                                                                                             |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|               | -   fgseaNES_combinedEfficacySafety\_[disease]\_[drug_target_type].rds (from DeNovo_data_1 directory)                                                                                                                                                                                                                                                                                                                                                               |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**    | -   predictions_NES_combinedEfficacySafety\_[disease]\_[drug_target_type].csv                                                                                                                                                                                                                                                                                                                                                                                       |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|               | -   priorityDrugCombs_NES_combinedEfficacySafety\_[disease]\_[drug_target_type].csv                                                                                                                                                                                                                                                                                                                                                                                 |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary**   | The script uses the predictive system developed in section 4.2 and the efficacy and safety estimates calculated in section 5.2 to generate predictions for the *de novo* data set drug combinations. The primary output is a data frame with the final score and the predicted categories along with other drug information. The script also identifies the top n (set using `select_top_combs` argument) candidates to be prioritised for experimental validation. |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
