---
title: 'Part 2: Preparing the enrichment libraries'
output: github_document
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This part deals with the scripts that are used to download associations of genes to adverse effects, diseases, pathways and other relevant phenotypes to build gene set libraries that are used for performing enrichment analysis or for calculating proximity within our framework. Here, library refer to a group of gene sets. The libraries are stored as R named list with list element being the gene sets. The genes are represented by their Ensembl IDs.

### 2.1. Retrieving the databases for curating the disease and adverse effect gene sets

+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_ADR.R](../Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_ADR.R)                                                                       |
|             |                                                                                                                                                                                                                                 |
|             | [Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_Diseases.R](../Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_Diseases.R)                                                             |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | -   ADRAlert2GENE2ID.xlsx (ADReCS)                                                                                                                                                                                              |
|             |                                                                                                                                                                                                                                 |
|             | -   curated_gene_disease_associations.tsv.gz (DisGeNet)                                                                                                                                                                         |
|             |                                                                                                                                                                                                                                 |
|             | -   associationByDatatypeDirect (Open Targets)                                                                                                                                                                                  |
|             |                                                                                                                                                                                                                                 |
|             | -   IntOGen-Drivers-20230531.zip (Intogen)                                                                                                                                                                                      |
|             |                                                                                                                                                                                                                                 |
|             | -   Disease_Signatures_from_GEO_up_2014.txt (Enrichr)                                                                                                                                                                           |
|             |                                                                                                                                                                                                                                 |
|             | -   relationships.zip (PharmGKB)                                                                                                                                                                                                |
|             |                                                                                                                                                                                                                                 |
|             | -   CTD_genes_diseases.csv.gz (Comparative Toxicogenomics Database)                                                                                                                                                             |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | -   ADReCS_ADR2Gene_level4_lib.rds                                                                                                                                                                                              |
|             |                                                                                                                                                                                                                                 |
|             | -   ADReCS_ADR2Gene_level3_lib.rds                                                                                                                                                                                              |
|             |                                                                                                                                                                                                                                 |
|             | -   DisGeNET_Disease2Gene_lib.rds                                                                                                                                                                                               |
|             |                                                                                                                                                                                                                                 |
|             | -   DisGeNET_Phenotype2Gene_lib.rds                                                                                                                                                                                             |
|             |                                                                                                                                                                                                                                 |
|             | -   DisGeNET_DiseaseGroup2Gene_lib.rds                                                                                                                                                                                          |
|             |                                                                                                                                                                                                                                 |
|             | -   OpenTargets_Disease2Gene_GA_lib.rds                                                                                                                                                                                         |
|             |                                                                                                                                                                                                                                 |
|             | -   OpenTargets_Disease2Gene_RNA_lib.rds                                                                                                                                                                                        |
|             |                                                                                                                                                                                                                                 |
|             | -   OpenTargets_Disease2Gene_lit_lib.rds                                                                                                                                                                                        |
|             |                                                                                                                                                                                                                                 |
|             | -   OpenTargets_Disease2Gene_SM_lib.rds                                                                                                                                                                                         |
|             |                                                                                                                                                                                                                                 |
|             | -   Intogen_Disease2Gene_lib.rds                                                                                                                                                                                                |
|             |                                                                                                                                                                                                                                 |
|             | -   Enrichr_Disease2Gene_GeoDiseaseSig_lib.rds                                                                                                                                                                                  |
|             |                                                                                                                                                                                                                                 |
|             | -   PharmGKB_Disease2Gene_lib.rds                                                                                                                                                                                               |
|             |                                                                                                                                                                                                                                 |
|             | -   CTD_Disease2Gene_lib.rds                                                                                                                                                                                                    |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | The scripts retrieves associations of genes to adverse effect and diseases as curated in different databases. Where ever possible, the types or the sources of the associations have been segregated and are stored separately. |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 2.2. Preparing disease specific libraries

+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Enrichment_analysis_libraries/Disease2Gene_BreastCancer_lib.R](../Scripts/Enrichment_analysis_libraries/Disease2Gene_BreastCancer_lib.R)     |
|             |                                                                                                                                                       |
|             | [Scripts/Enrichment_analysis_libraries/Disease2Gene_KidneyCancer_lib.R](../Scripts/Enrichment_analysis_libraries/Disease2Gene_KidneyCancer_lib.R)     |
|             |                                                                                                                                                       |
|             | [Scripts/Enrichment_analysis_libraries/Disease2Gene_LungCancer_lib.R](../Scripts/Enrichment_analysis_libraries/Disease2Gene_LungCancer_lib.R)         |
|             |                                                                                                                                                       |
|             | [Scripts/Enrichment_analysis_libraries/Disease2Gene_OvaryCancer_lib.R](../Scripts/Enrichment_analysis_libraries/Disease2Gene_OvaryCancer_lib.R)       |
|             |                                                                                                                                                       |
|             | [Scripts/Enrichment_analysis_libraries/Disease2Gene_ProstateCancer_lib.R](../Scripts/Enrichment_analysis_libraries/Disease2Gene_ProstateCancer_lib.R) |
|             |                                                                                                                                                       |
|             | [Scripts/Enrichment_analysis_libraries/Disease2Gene_SkinCancer_lib.R](../Scripts/Enrichment_analysis_libraries/Disease2Gene_SkinCancer_lib.R)         |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | -   DisGeNET_Disease2Gene_lib.rds                                                                                                                     |
|             |                                                                                                                                                       |
|             | -   OpenTargets_Disease2Gene_GA_lib.rds                                                                                                               |
|             |                                                                                                                                                       |
|             | -   OpenTargets_Disease2Gene_RNA_lib.rds                                                                                                              |
|             |                                                                                                                                                       |
|             | -   OpenTargets_Disease2Gene_lit_lib.rds                                                                                                              |
|             |                                                                                                                                                       |
|             | -   OpenTargets_Disease2Gene_SM_lib.rds                                                                                                               |
|             |                                                                                                                                                       |
|             | -   Enrichr_Disease2Gene_GeoDiseaseSig_lib.rds                                                                                                        |
|             |                                                                                                                                                       |
|             | -   Intogen_Disease2Gene_lib.rds                                                                                                                      |
|             |                                                                                                                                                       |
|             | -   PharmGKB_Disease2Gene_lib.rds                                                                                                                     |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | -   Disease2Gene_BreastCancer_lib.rds                                                                                                                 |
|             |                                                                                                                                                       |
|             | -   Disease2Gene_KidneyCancer_lib.rds                                                                                                                 |
|             |                                                                                                                                                       |
|             | -   Disease2Gene_LungCancer_lib.rds                                                                                                                   |
|             |                                                                                                                                                       |
|             | -   Disease2Gene_OvaryCancer_lib.rds                                                                                                                  |
|             |                                                                                                                                                       |
|             | -   Disease2Gene_ProstateCancer_lib.rds                                                                                                               |
|             |                                                                                                                                                       |
|             | -   Disease2Gene_SkinCancer_lib.rds                                                                                                                   |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | The scripts prepares six cancer type specific gene set libraries using the gene disease associations retrieved in section 2.1.                        |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+

### 2.3. Prepare the adverse effect linked gene set library

+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_curatedADR.R](../Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_curatedADR.R)                                                                                                               |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | -   ADReCS_ADR2Gene_level3_lib.rds                                                                                                                                                                                                                                                    |
|             |                                                                                                                                                                                                                                                                                       |
|             | -   ADReCS_ADR2Gene_level4_lib.rds                                                                                                                                                                                                                                                    |
|             |                                                                                                                                                                                                                                                                                       |
|             | -   CTD_Disease2Gene_lib.rds                                                                                                                                                                                                                                                          |
|             |                                                                                                                                                                                                                                                                                       |
|             | -   DisGeNET_Disease2Gene_lib.rds                                                                                                                                                                                                                                                     |
|             |                                                                                                                                                                                                                                                                                       |
|             | -   DisGeNET_DiseaseGroup2Gene_lib.rds                                                                                                                                                                                                                                                |
|             |                                                                                                                                                                                                                                                                                       |
|             | -   DisGeNET_Phenotype2Gene_lib.rds                                                                                                                                                                                                                                                   |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | -   curatedAdr2Gene_lib.rds                                                                                                                                                                                                                                                           |
|             |                                                                                                                                                                                                                                                                                       |
|             | -   curatedAdr2Gene_libInfo.xlsx                                                                                                                                                                                                                                                      |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | The script curates gene set library with the genes linked to adverse drug reactions that are frequently associated with drug withdrawal from the market and other relevant organ toxicities. The script also calculates the Jaccard similarity between the gene sets in this library, |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 2.4. Retrieving and prepare pathway related gene set libraries

+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_Pathways.R](../Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_Pathways.R)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | -   PMC7013921/Table_1.xls (PubMed Central)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|             | -   smpdb_proteins.csv.zip (SMPDB)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|             | -   smpdb_pathways.csv.zip (SMPDB)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | -   CHG_keggPath2Gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|             | -   SMPDb_Pathway2Gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | The script curates two library consisting of pathways from two different sources. The first library consists of cancer hallmark associated KEGG pathways. The list of characteristic KEGG pathways of different cancer hallmarker were retrieved from the research article [PMC7013921](https://doi.org/10.3389/fgene.2020.00029) while the genes in the KEGG pathway were sourced from the [KEGG database](https://www.genome.jp/kegg/). The second library is based on the pathways curated in the [Small Molecule Pathway Database (SMPDB)](https://www.smpdb.ca/). The library consists of two sub-libraries — one for the pathways associated to drug action while the other for pathways linked to drug metabolism. |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 2.5. Retrieve and prepare library consisting of miscellaneous gene sets

+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rscript** | [Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_Miscellaneous.R](../Scripts/Enrichment_analysis_libraries/Enrichment_Analysis_Libraries_Miscellaneous.R)                                                                                                                                                                                                                               |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Input**   | -   categories.tsv (DGIdb)                                                                                                                                                                                                                                                                                                                                                                                  |
|             |                                                                                                                                                                                                                                                                                                                                                                                                             |
|             | -   genes.zip (PharmGKB)                                                                                                                                                                                                                                                                                                                                                                                    |
|             |                                                                                                                                                                                                                                                                                                                                                                                                             |
|             | -   human_genes.zip (GenAge)                                                                                                                                                                                                                                                                                                                                                                                |
|             |                                                                                                                                                                                                                                                                                                                                                                                                             |
|             | -   suppl_data_baaa045.zip (PubMed)                                                                                                                                                                                                                                                                                                                                                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Output**  | miscellaneous_gene_lib.rds                                                                                                                                                                                                                                                                                                                                                                                  |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Summary** | The script curates a library by combining four independent gene sets — genes in drugable geneome from [Drug Gene Interaction Database (DGIdb)](https://www.dgidb.org/), very important pharmacogenes from [PharmGKB](https://www.pharmgkb.org/), genes related to ageing from [GenAge](https://genomics.senescence.info/genes/index.html) database and hallmarkers of cancer (HOC) genes from HOC database. |
|             |                                                                                                                                                                                                                                                                                                                                                                                                             |
|             | Note: To compile the HOC genes, the supplementary file 'Halifax-curation.Table S2. Hallmark of Cancer Data - Gene and Pathway.xlsx' must be manually downloaded from the research article [PMC7294774](https://doi.org/10.1093/database/baaa045) and placed inside the `Databases/HOCdb/` directory.                                                                                                        |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
